version: '3.8'

services:
  spd-reservation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spd-reservation-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
      # Google API credentials - replace with your actual values
      - GOOGLE_TYPE=service_account
      - GOOGLE_PROJECT_ID=seraphic-camp-464715-e6
      - GOOGLE_PRIVATE_KEY_ID=29afca6bcf94a6c21c081995330f5379954b549e
      - GOOGLE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCriS74i7k5V+/0\nuKWu7rxohj61noRlQEU1PGv4l9K5woUWZFqRRwDem7O6wTZ7ipv3Dim0DHgDWSal\nq976j86wk+sRYSqYZtdFTVlMORcSc69ZQtGvzxSliILqR3vdljDy9I1em42wUzW/\nuxQL/scyEzB5PUqCapzGDlmWjw2vRALO5ojWGfqIi0DY2xm1Yg3xLIwWmOacQu8f\ntvPz/LH7u/4j9jczV2SiCqls8pqghugY8iPznNhVgHKOD7qJYob4vblVeBs/JPgM\nwz6qO6u0XOZ5k/vPgvyAFYBgU7vm0hGcvlNGZ/NXVSgaxPRB6HNl/1noTbUaP60a\n83fyY5KpAgMBAAECggEACatzUXwGPkBh4hSu9FhNbdf+0iau4HVPIXPimJzYZR6H\nzu4WeUDnKzqxlvTG2+UsVcY/iBXkMGN2wq6YZIgK9wMeTyMVhLSsFyJH3HyNu314\nKaA9vqXTYbclvXa3pGi6dtZd33LbOdDLA3VUk+OHekrAzV4s5IKwNphUU7YvPOK7\n4nMVzQ18vdDfddJJTa+IybWwziMbl7CSwTnrQU/MVTcCwxH6zc7xEVitz6fhlEmU\nMDE8DmuVVqaYCoPvjefc1ReY2xzYo/O/rluAuYrXE5Ig1xe9YErr7/xgXvA0mOLc\nTE1UDZth/X5yNfXJQPc6wS/6K4/ZyL5no/Z5lT8hXQKBgQDXEkD2fpUAiEqG7QcR\n4BgZom7Ak+6XpvO/rNDP0mou1JyD9DiOsxpPJXmAF1hgeWmQ1nR3JHek018HzlX3\nBDkoRiikixmkHzPkKbpsXOgQy3CB8Ft8BINs0jNZbJ6UaQeBbx5Dcg4HZtJ/jILN\nAzgYCKlU91qoluBGdv7f2zdG/QKBgQDMLf2HSqDOdqgJILkDw5tsKcBl8Yed5F9x\nwPU5scNdrmsVixISjuOGSdUrCyUAH/pa34KYUPyCAfh8WQW44gzDkzndiBHa54hg\njBk1pKBeW+tmX9LdXzbdZI93PGFEFIrxzUZq1AbMC0YTYmDb1H3ZfaJJdV5KqEgV\n+XBJOv0oHQKBgQCeLG+Ymbnt/U6KcvJ7JAu1dq/rdCDKad/kfS3JWl/7dyRxK4EY\n+gIEaXQ1T3YQ5dpMylw3b5uKnmXKsOaqV/HNe+PSN/cwrD4WtNXFcoK+L1DcT7CI\nwi0CMInRX8A1OBVsDRP92HkW2nk/k1BzhMWRb3VR5uVHDkd9q3CBpJC/5QKBgCWs\nJqcbwefWRNLKUti68qZWXcVxdxBO3r1iWNy4S8+xKtjivAbojlpsrQQwHjeTruGt\nc68e4jgqnOp0knW2X5yGQZr6TDETnzoRH2WiZmSCmUBeVc26j6jxsPbTES86ixhq\nQ5/aVxa2zcstz6k/36iNYbAkE626tvI2/9zDIYqRAoGAcKviekJKMJ85M+qHM3jL\n6kFs7kG5gNT+qp6HIr8dd9uedv3ZIW2po5sObhuQKzUOyANqpF27Duot8M9yPpet\nvD5COGAgxYHerxVJ9IaRlE473sbiUOuZ9QhU67tr5ltySyDFQPvDGNFkIxBNsgFK\ng2ywsvy7iuGdTVJUO6nD1F8=\n-----END PRIVATE KEY-----\n
      - GOOGLE_CLIENT_EMAIL=roomreservation@seraphic-camp-464715-e6.iam.gserviceaccount.com
      - GOOGLE_CLIENT_ID=101756370978612681861
      - GOOGLE_AUTH_URI=https://accounts.google.com/o/oauth2/auth
      - GOOGLE_TOKEN_URI=https://oauth2.googleapis.com/token
      - GOOGLE_AUTH_PROVIDER_X509_CERT_URL=https://www.googleapis.com/oauth2/v1/certs
      - GOOGLE_CLIENT_X509_CERT_URL=https://www.googleapis.com/robot/v1/metadata/x509/roomreservation%40seraphic-camp-464715-e6.iam.gserviceaccount.com
      - GOOGLE_UNIVERSE_DOMAIN=googleapis.com
      - GOOGLE_SPREADSHEET_ID=1d-Aa9mZ3FGtIp43o3K4ljcwyQMwaaonaGO3abP5Pc-M
      - GOOGLE_SHEET_NAME=Bookings
    restart: unless-stopped
    networks:
      - spd-network
    volumes:
      # NAS persistent storage for logs
      - /volume1/docker/spd-reservation/logs:/app/logs
      # NAS persistent storage for backups
      - /volume1/docker/spd-reservation/backups:/app/backups
      # NAS persistent storage for config
      - /volume1/docker/spd-reservation/config:/app/config
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx reverse proxy for NAS deployment
  nginx:
    image: nginx:alpine
    container_name: spd-reservation-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /volume1/docker/spd-reservation/ssl:/etc/nginx/ssl:ro
      - /volume1/docker/spd-reservation/nginx/logs:/var/log/nginx
    depends_on:
      - spd-reservation
    restart: unless-stopped
    networks:
      - spd-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  spd-network:
    driver: bridge

volumes:
  logs:
    driver: local
  backups:
    driver: local
  config:
    driver: local 